spring:
  datasource:
    url: jdbc:h2:tcp://localhost/c:/h2db/logindb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace